\echo User :SCHEME_USERNAME
CREATE USER :SCHEME_USERNAME PASSWORD :'SCHEME_PASSWORD';
COMMIT;

\echo Create database :"DB_NAME" with owner :"SCHEME_USERNAME"
CREATE DATABASE :DB_NAME OWNER :SCHEME_USERNAME ENCODING 'UTF8' TABLESPACE :MAIN_TABLESPACE;

\echo Change Tablespaces :MAIN_TABLESPACE owner to :SCHEME_USERNAME
ALTER TABLESPACE :MAIN_TABLESPACE OWNER TO :SCHEME_USERNAME;

\echo Change Tablespaces :INDX_TABLESPACE owner to :SCHEME_USERNAME
ALTER TABLESPACE :INDX_TABLESPACE OWNER TO :SCHEME_USERNAME;

COMMIT;